apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erp-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/essanpupil/infra-code.git
    targetRevision: main
    path: kubernetes/erp
    helm:
      releaseName: erp
  destination:
    name: platform-stg-erp
    namespace: erp
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
