apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: business-applications
    app.kubernetes.io/name: pos
spec:
  project: default
  source:
    repoURL: https://github.com/essanpupil/infra-code.git
    targetRevision: main
    path: kubernetes/pos
    helm:
      releaseName: pos
  destination:
    name: platform-dev-pos
    namespace: pos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
