apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/essanpupil/infra-code.git
    targetRevision: main
    path: kubernetes/pos
    helm:
      releaseName: pos
  destination:
    name: platform-prod-pos
    namespace: pos
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
