apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erp.fullname" . }}
  labels:
    {{- include "erp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: erp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessPath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessPath }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
